# Generated by Django 3.2.9 on 2021-11-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название блога')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('discription', models.TextField(blank=True, verbose_name='описание блога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='картинка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='статус публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('-date_created', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(verbose_name='коментарий')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='статус публикации')),
                ('author', models.CharField(max_length=300, null=True, verbose_name='автор')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='блог')),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'коментарии',
                'ordering': ('-date_create',),
            },
        ),
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='слаг')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя блогера')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия блогера')),
                ('bio', models.TextField(max_length=200, null=True, verbose_name='инфо о блогере')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('is_published', models.BooleanField(default=False, verbose_name='статус блогера')),
                ('pseudonym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='псевдоним')),
            ],
            options={
                'verbose_name': 'блогер',
                'verbose_name_plural': 'блогеры',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bloger', verbose_name='автор блога'),
        ),
    ]
