# Generated by Django 3.2.9 on 2022-01-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='статус блогера'),
        ),
    ]
