# Generated by Django 3.2.9 on 2022-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bloger_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
        ),
    ]
